title: "[LIVE EVENT] BlackCat Reconnaissance Functions - Live Demo Against Production Environment"
labels: ["live-event", "demonstration", "reconnaissance"]
body:
  - type: markdown
    attributes:
      value: |
        # 🎯 Live Event: BlackCat Reconnaissance Capabilities Demo

        ![BlackCat Logo](/.github/media/cateye.png?raw=true)

        ## 📅 Event Overview

        Join us for an interactive live demonstration showcasing the powerful reconnaissance capabilities of the **BlackCat** PowerShell module against a live Azure environment. This session is designed for security professionals and IT administrators who want to understand how to identify potential security risks in Microsoft Azure environments.

        ### 🎓 Target Audience
        - Security Professionals
        - IT Administrators
        - Azure Security Engineers
        - Penetration Testers
        - Cloud Security Architects
        - DevSecOps Engineers

        ---

        ## 🔍 Reconnaissance Functions We'll Demonstrate

        ### Authenticated Reconnaissance Functions

        #### 1. **Get-EntraRoleMember**
        - **Purpose**: Enumerate all members of Microsoft Entra ID (Azure AD) privileged roles
        - **Use Case**: Identify users with elevated permissions, detect shadow admins
        - **Live Demo**: We'll show how to discover all Global Administrators and other privileged role assignments

        #### 2. **Get-EntraIDPermissions**
        - **Purpose**: List all permissions a user or group has in Microsoft Entra ID
        - **Use Case**: Understand the full permission footprint of identities
        - **Live Demo**: Analyze permission assignments for service principals and users

        #### 3. **Get-EntraInformation**
        - **Purpose**: Retrieve detailed information about Azure AD users or groups
        - **Use Case**: Profile user accounts and group memberships
        - **Live Demo**: Extract user attributes, group memberships, and relationships

        #### 4. **Get-ManagedIdentity**
        - **Purpose**: Discover Azure Managed Identities across subscriptions
        - **Use Case**: Identify system and user-assigned managed identities
        - **Live Demo**: Map managed identities to Azure resources

        #### 5. **Get-StorageContainerList**
        - **Purpose**: List all storage containers from Azure Storage Accounts
        - **Use Case**: Audit storage resources and identify potential data exposure
        - **Live Demo**: Enumerate containers and check access configurations

        #### 6. **Get-AdministrativeUnit**
        - **Purpose**: Retrieve information about Azure AD Administrative Units
        - **Use Case**: Understand delegated administration boundaries
        - **Live Demo**: Map administrative units and their scoped administrators

        #### 7. **Invoke-AzBatch**
        - **Purpose**: Execute Azure Resource Graph queries using batch requests with caching
        - **Use Case**: Perform efficient large-scale resource queries
        - **Live Demo**: Batch query multiple subscriptions for resource inventory

        #### 8. **Invoke-MSGraph**
        - **Purpose**: Direct interaction with Microsoft Graph API
        - **Use Case**: Custom queries and advanced data retrieval
        - **Live Demo**: Execute complex Graph API queries for deep reconnaissance

        ---

        ### Anonymous Reconnaissance Functions (No Authentication Required)

        #### 9. **Find-SubDomain**
        - **Purpose**: Discover active subdomains through DNS resolution
        - **Use Case**: Map external attack surface, identify forgotten resources
        - **Live Demo**: Enumerate subdomains for a target organization

        #### 10. **Find-DnsRecords**
        - **Purpose**: Comprehensive DNS reconnaissance with provider support
        - **Use Case**: Gather DNS intelligence, identify misconfigurations
        - **Live Demo**: Perform DNS enumeration across multiple record types

        #### 11. **Find-PublicStorageContainer**
        - **Purpose**: Locate publicly accessible Azure Storage containers
        - **Use Case**: Identify data exposure risks from misconfigured storage
        - **Live Demo**: Search for publicly accessible storage accounts

        #### 12. **Find-AzurePublicResource**
        - **Purpose**: Discover publicly accessible Azure resources
        - **Use Case**: Enumerate externally facing services and endpoints
        - **Live Demo**: Map public-facing Azure infrastructure

        ---

        ## 💡 What You'll Learn

        - How to install and configure the BlackCat module
        - Proper authentication and connection to Azure environments
        - Best practices for responsible reconnaissance
        - How to interpret and analyze reconnaissance results
        - Common security misconfigurations discovered through these functions
        - Remediation strategies for identified security risks
        - Integration with security assessment workflows

        ---

        ## 🛠️ Prerequisites for Participants

        To follow along during the live event, please ensure you have:

        - **PowerShell 7.0 or higher** (Windows PowerShell 5.1 is NOT supported)
        - **Az.Accounts module** installed
        - **BlackCat module** installed from PSGallery:
          ```powershell
          Install-Module BlackCat
          Import-Module BlackCat
          ```
        - Access to an Azure environment (test/lab environment recommended)
        - Appropriate permissions to run reconnaissance commands

        ---

        ## 📋 Event Agenda

        1. **Introduction** (10 minutes)
           - Overview of BlackCat module
           - Security context and ethical considerations

        2. **Environment Setup** (15 minutes)
           - Module installation and configuration
           - Azure authentication
           - Permissions verification

        3. **Authenticated Reconnaissance Demo** (45 minutes)
           - Entra ID role enumeration
           - Permission analysis
           - Identity and access discovery
           - Resource reconnaissance

        4. **Anonymous Reconnaissance Demo** (30 minutes)
           - External attack surface mapping
           - DNS reconnaissance techniques
           - Public resource discovery

        5. **Analysis and Findings** (20 minutes)
           - Review discovered security issues
           - Risk assessment
           - Remediation recommendations

        6. **Q&A and Discussion** (20 minutes)
           - Open discussion
           - Community questions
           - Feature requests

        ---

        ## ⚠️ Important Security Considerations

        - **Authorization Required**: Always ensure you have proper authorization before running reconnaissance against any environment
        - **Legal Compliance**: Only use these tools against environments you own or have explicit permission to test
        - **Responsible Disclosure**: Any vulnerabilities discovered should be responsibly disclosed
        - **Ethical Use**: This module is designed for defensive security purposes only

        ---

        ## 🔗 Additional Resources

        - [BlackCat GitHub Repository](https://github.com/azurekid/blackcat)
        - [Project Backlog](https://github.com/users/azurekid/projects/3/views/1)
        - [PowerShell Gallery Package](https://www.powershellgallery.com/packages/BlackCat)
        - [Documentation](https://github.com/azurekid/blackcat/blob/main/README.md)

  - type: input
    id: event-date
    attributes:
      label: "📅 Proposed Event Date and Time"
      description: "When would you like to schedule this live event? (Please include timezone)"
      placeholder: "e.g., 2025-11-15 14:00 UTC or Multiple dates for global coverage"
    validations:
      required: true

  - type: dropdown
    id: event-format
    attributes:
      label: "🎥 Preferred Event Format"
      description: "How would you like to participate in this event?"
      multiple: true
      options:
        - Live streaming (YouTube/Twitch)
        - Interactive webinar (Zoom/Teams)
        - In-person workshop
        - Recorded with live Q&A
        - GitHub Discussions thread
    validations:
      required: true

  - type: dropdown
    id: experience-level
    attributes:
      label: "📊 Your Experience Level"
      description: "What is your current experience with Azure security?"
      options:
        - Beginner (New to Azure Security)
        - Intermediate (Some Azure security experience)
        - Advanced (Regular security assessments)
        - Expert (Professional penetration tester/security architect)
    validations:
      required: false

  - type: textarea
    id: specific-functions
    attributes:
      label: "🎯 Functions of Interest"
      description: "Which reconnaissance functions are you most interested in seeing demonstrated?"
      placeholder: |
        e.g.,
        - Find-SubDomain - Want to learn about external attack surface mapping
        - Get-EntraRoleMember - Need to audit privileged access in my org
        - Find-PublicStorageContainer - Concerned about data exposure
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: "💼 Your Use Cases"
      description: "What specific use cases or scenarios would you like us to cover?"
      placeholder: |
        Share your specific requirements or scenarios, such as:
        - Compliance auditing
        - Red team assessments
        - Cloud security posture management
        - Incident response
    validations:
      required: false

  - type: textarea
    id: questions
    attributes:
      label: "❓ Questions or Topics"
      description: "Do you have specific questions or topics you'd like addressed during the event?"
      placeholder: "Feel free to ask anything related to reconnaissance, Azure security, or the BlackCat module"
    validations:
      required: false

  - type: checkboxes
    id: notification-preferences
    attributes:
      label: "🔔 Notification Preferences"
      description: "How would you like to be notified about this event?"
      options:
        - label: "Watch this discussion for updates"
        - label: "Subscribe to repository notifications"
        - label: "Interested in future security events"

  - type: markdown
    attributes:
      value: |
        ---

        ## 🤝 Get Involved

        We welcome community input on this event! Please share:
        - Your availability and timezone preferences
        - Functions you're most interested in
        - Real-world use cases from your experience
        - Suggestions for the demo scenarios

        **Let's make this a valuable learning experience for the entire security community!** 🚀

        ---

        ### 📢 Stay Updated

        - Star the repository to get notifications
        - Watch this discussion for event announcements
        - Follow the project for future events and updates

        ### 🙏 Support the Project

        If you find BlackCat useful, please consider:
        - ⭐ Starring the repository
        - 🐛 Reporting issues or bugs
        - 💡 Suggesting new features
        - 🤝 Contributing code or documentation
        - 📣 Sharing with your security community
