name: Publish Module
on:
  workflow_dispatch:

jobs:
  sign_scripts:
    name: Sign and publish PowerShell scripts as pipeline artifacts
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Sign and Publish Module
        shell: pwsh
        env:
          PS_GALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
        run: |
          Write-Host "Publishing module to PowerShell Gallery"

          $tempPath = New-Item -Path .\src\BlackCat\ -ItemType Directory -Force

          # publish module
          Write-Host "Publishing module to PowerShell Gallery"

          # Set the path to the module
          Copy-Item .\BlackCat.psd1 -Destination $tempPath -Force
          Copy-Item .\BlackCat.psm1 -Destination $tempPath -Force
          Copy-Item .\Private -Recurse -Destination $tempPath -Force
          Copy-Item .\Public -Recurse -Destination $tempPath -Force


          # Create empty .moduledata directory to prevent NuGet warnings
          New-Item -Path "$tempPath\.moduledata" -ItemType Directory -Force | Out-Null
          
          # Create an info file to suppress NuGet warnings
          Set-Content -Path "$tempPath\.moduledata\moduleinfo.txt" -Value "This file suppresses NuGet warnings about PowerShell scripts."
          
          # Suppress NuGet warnings by setting environment variables
          $env:NUGET_XMLDOC_MODE = "skip"
          
          # Set warning preference to suppress warnings
          $WarningPreference = 'SilentlyContinue'
          
          # Publish module with warning suppression
          Write-Host "Publishing module to PowerShell Gallery..."
          Publish-Module -Path "$tempPath" -NuGetApiKey $env:PS_GALLERY_KEY -Force -WarningAction SilentlyContinue
          
          # Remove the module from the local system
          Remove-Item -Path $tempPath -Recurse -Force -ErrorAction SilentlyContinue